---
title: "Dashboard Proposal <br> *Criminality in Canada: Fighting Anecdotes with Data*"
output: 
  github_document:
    toc: yes
    number_sections: yes
---

# Motivation and purpose

**Our Role:** Data scientists at a consultancy firm.

**Target Audience:** General public.

The public's understanding of the distribution and prevalence of crime in Canada is often not based on the robust data collected by police departments around the country.  Instead, people's knowledge of crime is often derived from stories circulating through communities and stories presented in the media.  Both these sources of information have significant limitations.  For example, a given person will only hear about a small percentage of total crimes committed across the nation through the media or through community connections.  Additionally, crimes that are violent or otherwise sensational are often overrepresented.  

In order to foster an understanding of crime that is more comprehensive and less biased, our team will create a dashboard which allows the public to easily view and explore Canadian crime data.  These data will be derived from Statistics Canada.  The dashboard should be easy to navigate for someone from the general population and provide summary information in a way that is easy to interpret.  The dashboard should be interactive and allow users to explore types, locations, and frequency of crimes committed as well as the time period in which they occurred.

# Description of data

Text

# Research questions and usage scenarios

**Sample usage scenario:**
Jane and her family are planning to move to Canada and are deciding where they will live.  Living in an area with a low rate of violent crime is important to her.  Jane has heard stories in the news about crime in various parts of Canada but wants to make sure she is making her decision based on reliable information.  Jane accesses the "Criminality in Canada: Fighting Anecdotes with Data" dashboard to [learn] more about violent crime rates in Canada.  Jane would like to live near the mountains so she [limits] the crime rate data she is viewing to areas in Alberta, British Columbia, Quebec, Northwest Territories, Yukon, and Nunavut.  Jane is primarily concerned with violent crimes so she [excludes] all other types of crime from.  Jane is now able to [explore] a map on the ‘Geographic Crime Trends’ tab of the dashboard which shows the relative violent crime rates in her areas of interest.  Jane chooses the 10 regions having the lowest violent crime rates and does some more research on these areas.  Based on factors other than violent crime rates, she narrows her list down to 5.  Jane understands that crime rates are not static so wants to understand whether violent crime has been increasing or decreasing recently.  Jane opens the ‘Crime Time Trends’ tab of the dashboard and views a plot showing the violent crime rates over the past 5 years.  Identifying the region in which the violent crime rate is decreasing the fastest, Jane is able to decide where in Canada she and her family will settle.